WIP - Use official Microstrain driver
jackal/jackal_robot pull request #40
Opened 2021-11-20 02:09 UTC by civerachb-cpr

LORD has released the former `ros_mscl` driver under the name `microstrain_inertial_driver`.  Switch the accessories to use the official driver instead of our interim fork.
This PR is marked as WIP until we have the chance to test the sensor on the robot to make sure everything works correctly before merging.

2021-11-23 19:13 UTC, tonybaltovski requested changes

2021-11-23 19:13 UTC, tonybaltovski commented on jackal_bringup/package.xml
> +  <run_depend>microstrain_inertial_driver</run_depend>
Minor nit, alphabetical order.

2021-11-26 17:21 UTC, civerachb-cpr commented on jackal_bringup/package.xml
> +  <run_depend>microstrain_inertial_driver</run_depend>
Done

2022-11-25 17:04 UTC, tonybaltovski commented
Was done in https://github.com/jackal/jackal_robot/pull/61

2022-11-25 17:04 UTC, closed without merging